server:
  port: 80
  servlet:
    encoding: 
      charset: utf-8
      force: true 

spring: 
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/kender_rent?serverTimeZone=Asia/Seoul 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
    h2:
    console:
      enabled: false  # H2 콘솔 비활성화
# sql:
#  init:
#    schema-locations:
#      classpath:db/table.sql
#    data-locations:
#      classpath:db/data.sql
  #h2: 
  #  console:
  #    enabled: true
  #  output: 
  #    ansi:
  #    enabled: always

mybatis:
 mapper-locations:
  classpath:mapper/**.xml
 configuration:
  map-underscore-to-camel-case: true
  
logging:
 level:
  org.mybatis: DEBUG